apiVersion: v2
name: aic-connector-cv
description: Helm chart for processing detections for ai cockpit in valkey and save videos to minio

# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: ""
